theme("Логічні оператори");
quest("Яке значення логічного виразу <b>not(0)</b> ?//a");
rep("(o) 1");
rep("( ) 0");
quest("Яке значення логічного виразу <b>not(1)</b> ?//a");
rep("( ) 1");
rep("(o) 0");
quest("Яке значення логічного виразу <b>not(1)</b> ?//a");
rep("( ) 1");
rep("(o) 0");
quest("Яке значення логічного виразу <b>not(0)</b> ?//a");
rep("(o) 1");
rep("( ) 0");
quest("Яке значення логічного виразу <b>0 and 1</b> ?//a");
rep("( ) 1");
rep("(o) 0");
quest("Яке значення логічного виразу <b>1 and 0</b> ?//a");
rep("( ) 1");
rep("(o) 0");
quest("Яке значення логічного виразу <b>0 or 1</b> ?//a");
rep("(o) 1");
rep("( ) 0");
quest("Яке значення логічного виразу <b>1 or 0</b> ?//a");
rep("(o) 1");
rep("( ) 0");
quest("Яке значення логічного виразу <b>0 xor 1</b> ?//a");
rep("(o) 1");
rep("( ) 0");
quest("Яке значення логічного виразу <b>1 xor 0</b> ?//a");
rep("(o) 1");
rep("( ) 0");
quest("Яке значення логічного виразу <b>0 or 1 and 1</b> ?//a");
rep("(o) 1");
rep("( ) 0");
quest("Яке значення логічного виразу <b>1 or 1 and 0</b> ?//a");
rep("(o) 1");
rep("( ) 0");
quest("Яке значення логічного виразу <b>0 and 1 or 1</b> ?//a");
rep("(o) 1");
rep("( ) 0");
quest("Яке значення логічного виразу <b>1 and 1 or 0</b> ?//a");
rep("(o) 1");
rep("( ) 0");
quest("Яке значення логічного виразу <b>(0 or 1) and 1</b> ?//a");
rep("(o) 1");
rep("( ) 0");
quest("Яке значення логічного виразу <b>(1 or 1) and 0</b> ?//a");
rep("( ) 1");
rep("(o) 0");
quest("Яке значення логічного виразу <b>0 and (1 or 1)</b> ?//a");
rep("( ) 1");
rep("(o) 0");
quest("Яке значення логічного виразу <b>1 and (1 or 0)</b> ?//a");
rep("(o) 1");
rep("( ) 0");
quest("Яке значення логічного виразу <b>0 xor 1 and 1</b> ?//a");
rep("(o) 1");
rep("( ) 0");
quest("Яке значення логічного виразу <b>1 xor 1 and 0</b> ?//a");
rep("(o) 1");
rep("( ) 0");
quest("Яке значення логічного виразу <b>0 and 1 xor 1</b> ?//a");
rep("(o) 1");
rep("( ) 0");
quest("Яке значення логічного виразу <b>1 and 1 xor 0</b> ?//a");
rep("(o) 1");
rep("( ) 0");
quest("Яке значення логічного виразу <b>(0 xor 1) and 1</b> ?//a");
rep("(o) 1");
rep("( ) 0");
quest("Яке значення логічного виразу <b>(1 xor 1) and 0</b> ?//a");
rep("( ) 1");
rep("(o) 0");
quest("Яке значення логічного виразу <b>0 and (1 xor 1)</b> ?//a");
rep("( ) 1");
rep("(o) 0");
quest("Яке значення логічного виразу <b>1 and (1 xor 0)</b> ?//a");
rep("(o) 1");
rep("( ) 0");
quest("Яке значення логічного виразу <b>(0 or 1) and (1 xor 0)</b> ?//a");
rep("(o) 1");
rep("( ) 0");
quest("Яке значення логічного виразу <b>not(0 or 1) and (1 xor 0)</b> ?//a");
rep("( ) 1");
rep("(o) 0");
quest("Яке значення логічного виразу <b>(0 or 1) and not(1 xor 0)</b> ?//a");
rep("( ) 1");
rep("(o) 0");
quest("Яке значення логічного виразу <b>not(0 or 1) and not(1 xor 0)</b> ?//a");
rep("( ) 1");
rep("(o) 0");
quest("Яке значення логічного виразу <b>(0 and 1) or (1 xor 0)</b> ?//a");
rep("(o) 1");
rep("( ) 0");
quest("Яке значення логічного виразу <b>not(0 and 1) or (1 xor 0)</b> ?//a");
rep("(o) 1");
rep("( ) 0");
quest("Яке значення логічного виразу <b>(0 and 1) or not(1 xor 0)</b> ?//a");
rep("( ) 1");
rep("(o) 0");
quest("Яке значення логічного виразу <b>not(0 and 1) or not(1 xor 0)</b> ?//a");
rep("(o) 1");
rep("( ) 0");
quest("Яке значення логічного виразу <b>(0 or 1) and (1 or 0)</b> ?//a");
rep("(o) 1");
rep("( ) 0");
quest("Яке значення логічного виразу <b>not(0 or 1) and (1 or 0)</b> ?//a");
rep("( ) 1");
rep("(o) 0");
quest("Яке значення логічного виразу <b>(0 or 1) and not(1 or 0)</b> ?//a");
rep("( ) 1");
rep("(o) 0");
quest("Яке значення логічного виразу <b>not(0 or 1) and not(1 or 0)</b> ?//a");
rep("( ) 1");
rep("(o) 0");
quest("Яке значення логічного виразу <b>(0 and 1) or (1 or 0)</b> ?//a");
rep("(o) 1");
rep("( ) 0");
quest("Яке значення логічного виразу <b>not(0 and 1) or (1 or 0)</b> ?//a");
rep("(o) 1");
rep("( ) 0");
quest("Яке значення логічного виразу <b>(0 and 1) or not(1 or 0)</b> ?//a");
rep("( ) 1");
rep("(o) 0");
quest("Яке значення логічного виразу <b>not(0 and 1) or not(1 or 0)</b> ?//a");
rep("(o) 1");
rep("( ) 0");
quest("Яке значення логічного виразу <b>not(1)</b> ?//a");
rep("( ) 1");
rep("(o) 0");
quest("Яке значення логічного виразу <b>not(0)</b> ?//a");
rep("(o) 1");
rep("( ) 0");
quest("Яке значення логічного виразу <b>not(1)</b> ?//a");
rep("( ) 1");
rep("(o) 0");
quest("Яке значення логічного виразу <b>not(0)</b> ?//a");
rep("(o) 1");
rep("( ) 0");
quest("Яке значення логічного виразу <b>1 and 0</b> ?//a");
rep("( ) 1");
rep("(o) 0");
quest("Яке значення логічного виразу <b>1 and 0</b> ?//a");
rep("( ) 1");
rep("(o) 0");
quest("Яке значення логічного виразу <b>1 or 0</b> ?//a");
rep("(o) 1");
rep("( ) 0");
quest("Яке значення логічного виразу <b>1 or 0</b> ?//a");
rep("(o) 1");
rep("( ) 0");
quest("Яке значення логічного виразу <b>1 xor 0</b> ?//a");
rep("(o) 1");
rep("( ) 0");
quest("Яке значення логічного виразу <b>1 xor 0</b> ?//a");
rep("(o) 1");
rep("( ) 0");
quest("Яке значення логічного виразу <b>1 or 0 and 1</b> ?//a");
rep("(o) 1");
rep("( ) 0");
quest("Яке значення логічного виразу <b>0 or 1 and 0</b> ?//a");
rep("( ) 1");
rep("(o) 0");
quest("Яке значення логічного виразу <b>1 and 0 or 1</b> ?//a");
rep("(o) 1");
rep("( ) 0");
quest("Яке значення логічного виразу <b>0 and 1 or 0</b> ?//a");
rep("( ) 1");
rep("(o) 0");
quest("Яке значення логічного виразу <b>(1 or 0) and 1</b> ?//a");
rep("(o) 1");
rep("( ) 0");
quest("Яке значення логічного виразу <b>(0 or 1) and 0</b> ?//a");
rep("( ) 1");
rep("(o) 0");
quest("Яке значення логічного виразу <b>1 and (0 or 1)</b> ?//a");
rep("(o) 1");
rep("( ) 0");
quest("Яке значення логічного виразу <b>0 and (1 or 0)</b> ?//a");
rep("( ) 1");
rep("(o) 0");
quest("Яке значення логічного виразу <b>1 xor 0 and 1</b> ?//a");
rep("(o) 1");
rep("( ) 0");
quest("Яке значення логічного виразу <b>0 xor 1 and 0</b> ?//a");
rep("( ) 1");
rep("(o) 0");
quest("Яке значення логічного виразу <b>1 and 0 xor 1</b> ?//a");
rep("(o) 1");
rep("( ) 0");
quest("Яке значення логічного виразу <b>0 and 1 xor 0</b> ?//a");
rep("( ) 1");
rep("(o) 0");
quest("Яке значення логічного виразу <b>(1 xor 0) and 1</b> ?//a");
rep("(o) 1");
rep("( ) 0");
quest("Яке значення логічного виразу <b>(0 xor 1) and 0</b> ?//a");
rep("( ) 1");
rep("(o) 0");
quest("Яке значення логічного виразу <b>1 and (0 xor 1)</b> ?//a");
rep("(o) 1");
rep("( ) 0");
quest("Яке значення логічного виразу <b>0 and (1 xor 0)</b> ?//a");
rep("( ) 1");
rep("(o) 0");
quest("Яке значення логічного виразу <b>(1 or 0) and (1 xor 0)</b> ?//a");
rep("(o) 1");
rep("( ) 0");
quest("Яке значення логічного виразу <b>not(1 or 0) and (1 xor 0)</b> ?//a");
rep("( ) 1");
rep("(o) 0");
quest("Яке значення логічного виразу <b>(1 or 0) and not(1 xor 0)</b> ?//a");
rep("( ) 1");
rep("(o) 0");
quest("Яке значення логічного виразу <b>not(1 or 0) and not(1 xor 0)</b> ?//a");
rep("( ) 1");
rep("(o) 0");
quest("Яке значення логічного виразу <b>(1 and 0) or (1 xor 0)</b> ?//a");
rep("(o) 1");
rep("( ) 0");
quest("Яке значення логічного виразу <b>not(1 and 0) or (1 xor 0)</b> ?//a");
rep("(o) 1");
rep("( ) 0");
quest("Яке значення логічного виразу <b>(1 and 0) or not(1 xor 0)</b> ?//a");
rep("( ) 1");
rep("(o) 0");
quest("Яке значення логічного виразу <b>not(1 and 0) or not(1 xor 0)</b> ?//a");
rep("(o) 1");
rep("( ) 0");
quest("Яке значення логічного виразу <b>(1 or 0) and (1 or 0)</b> ?//a");
rep("(o) 1");
rep("( ) 0");
quest("Яке значення логічного виразу <b>not(1 or 0) and (1 or 0)</b> ?//a");
rep("( ) 1");
rep("(o) 0");
quest("Яке значення логічного виразу <b>(1 or 0) and not(1 or 0)</b> ?//a");
rep("( ) 1");
rep("(o) 0");
quest("Яке значення логічного виразу <b>not(1 or 0) and not(1 or 0)</b> ?//a");
rep("( ) 1");
rep("(o) 0");
quest("Яке значення логічного виразу <b>(1 and 0) or (1 or 0)</b> ?//a");
rep("(o) 1");
rep("( ) 0");
quest("Яке значення логічного виразу <b>not(1 and 0) or (1 or 0)</b> ?//a");
rep("(o) 1");
rep("( ) 0");
quest("Яке значення логічного виразу <b>(1 and 0) or not(1 or 0)</b> ?//a");
rep("( ) 1");
rep("(o) 0");
quest("Яке значення логічного виразу <b>not(1 and 0) or not(1 or 0)</b> ?//a");
rep("(o) 1");
rep("( ) 0");
quest("Яке значення логічного виразу <b>not(True)</b> ?//a");
rep("( ) True");
rep("(o) False");
quest("Яке значення логічного виразу <b>not(False)</b> ?//a");
rep("(o) True");
rep("( ) False");
quest("Яке значення логічного виразу <b>not(False)</b> ?//a");
rep("(o) True");
rep("( ) False");
quest("Яке значення логічного виразу <b>not(True)</b> ?//a");
rep("( ) True");
rep("(o) False");
quest("Яке значення логічного виразу <b>True and False</b> ?//a");
rep("( ) True");
rep("(o) False");
quest("Яке значення логічного виразу <b>False and True</b> ?//a");
rep("( ) True");
rep("(o) False");
quest("Яке значення логічного виразу <b>True or False</b> ?//a");
rep("(o) True");
rep("( ) False");
quest("Яке значення логічного виразу <b>False or True</b> ?//a");
rep("(o) True");
rep("( ) False");
quest("Яке значення логічного виразу <b>True xor False</b> ?//a");
rep("(o) True");
rep("( ) False");
quest("Яке значення логічного виразу <b>False xor True</b> ?//a");
rep("(o) True");
rep("( ) False");
quest("Яке значення логічного виразу <b>True or False and False</b> ?//a");
rep("(o) True");
rep("( ) False");
quest("Яке значення логічного виразу <b>False or False and True</b> ?//a");
rep("( ) True");
rep("(o) False");
quest("Яке значення логічного виразу <b>True and False or False</b> ?//a");
rep("( ) True");
rep("(o) False");
quest("Яке значення логічного виразу <b>False and False or True</b> ?//a");
rep("(o) True");
rep("( ) False");
quest("Яке значення логічного виразу <b>(True or False) and False</b> ?//a");
rep("( ) True");
rep("(o) False");
quest("Яке значення логічного виразу <b>(False or False) and True</b> ?//a");
rep("( ) True");
rep("(o) False");
quest("Яке значення логічного виразу <b>True and (False or False)</b> ?//a");
rep("( ) True");
rep("(o) False");
quest("Яке значення логічного виразу <b>False and (False or True)</b> ?//a");
rep("( ) True");
rep("(o) False");
quest("Яке значення логічного виразу <b>True xor False and False</b> ?//a");
rep("(o) True");
rep("( ) False");
quest("Яке значення логічного виразу <b>False xor False and True</b> ?//a");
rep("( ) True");
rep("(o) False");
quest("Яке значення логічного виразу <b>True and False xor False</b> ?//a");
rep("( ) True");
rep("(o) False");
quest("Яке значення логічного виразу <b>False and False xor True</b> ?//a");
rep("(o) True");
rep("( ) False");
quest("Яке значення логічного виразу <b>(True xor False) and False</b> ?//a");
rep("( ) True");
rep("(o) False");
quest("Яке значення логічного виразу <b>(False xor False) and True</b> ?//a");
rep("( ) True");
rep("(o) False");
quest("Яке значення логічного виразу <b>True and (False xor False)</b> ?//a");
rep("( ) True");
rep("(o) False");
quest("Яке значення логічного виразу <b>False and (False xor True)</b> ?//a");
rep("( ) True");
rep("(o) False");
quest("Яке значення логічного виразу <b>(True or False) and (False xor True)</b> ?//a");
rep("(o) True");
rep("( ) False");
quest("Яке значення логічного виразу <b>not(True or False) and (False xor True)</b> ?//a");
rep("( ) True");
rep("(o) False");
quest("Яке значення логічного виразу <b>(True or False) and not(False xor True)</b> ?//a");
rep("( ) True");
rep("(o) False");
quest("Яке значення логічного виразу <b>not(True or False) and not(False xor True)</b> ?//a");
rep("( ) True");
rep("(o) False");
quest("Яке значення логічного виразу <b>(True and False) or (False xor True)</b> ?//a");
rep("(o) True");
rep("( ) False");
quest("Яке значення логічного виразу <b>not(True and False) or (False xor True)</b> ?//a");
rep("(o) True");
rep("( ) False");
quest("Яке значення логічного виразу <b>(True and False) or not(False xor True)</b> ?//a");
rep("( ) True");
rep("(o) False");
quest("Яке значення логічного виразу <b>not(True and False) or not(False xor True)</b> ?//a");
rep("(o) True");
rep("( ) False");
quest("Яке значення логічного виразу <b>(True or False) and (False or True)</b> ?//a");
rep("(o) True");
rep("( ) False");
quest("Яке значення логічного виразу <b>not(True or False) and (False or True)</b> ?//a");
rep("( ) True");
rep("(o) False");
quest("Яке значення логічного виразу <b>(True or False) and not(False or True)</b> ?//a");
rep("( ) True");
rep("(o) False");
quest("Яке значення логічного виразу <b>not(True or False) and not(False or True)</b> ?//a");
rep("( ) True");
rep("(o) False");
quest("Яке значення логічного виразу <b>(True and False) or (False or True)</b> ?//a");
rep("(o) True");
rep("( ) False");
quest("Яке значення логічного виразу <b>not(True and False) or (False or True)</b> ?//a");
rep("(o) True");
rep("( ) False");
quest("Яке значення логічного виразу <b>(True and False) or not(False or True)</b> ?//a");
rep("( ) True");
rep("(o) False");
quest("Яке значення логічного виразу <b>not(True and False) or not(False or True)</b> ?//a");
rep("(o) True");
rep("( ) False");
quest("Яке значення логічного виразу <b>not(False)</b> ?//a");
rep("(o) True");
rep("( ) False");
quest("Яке значення логічного виразу <b>not(False)</b> ?//a");
rep("(o) True");
rep("( ) False");
quest("Яке значення логічного виразу <b>not(False)</b> ?//a");
rep("(o) True");
rep("( ) False");
quest("Яке значення логічного виразу <b>not(False)</b> ?//a");
rep("(o) True");
rep("( ) False");
quest("Яке значення логічного виразу <b>False and False</b> ?//a");
rep("( ) True");
rep("(o) False");
quest("Яке значення логічного виразу <b>False and False</b> ?//a");
rep("( ) True");
rep("(o) False");
quest("Яке значення логічного виразу <b>False or False</b> ?//a");
rep("( ) True");
rep("(o) False");
quest("Яке значення логічного виразу <b>False or False</b> ?//a");
rep("( ) True");
rep("(o) False");
quest("Яке значення логічного виразу <b>False xor False</b> ?//a");
rep("( ) True");
rep("(o) False");
quest("Яке значення логічного виразу <b>False xor False</b> ?//a");
rep("( ) True");
rep("(o) False");
quest("Яке значення логічного виразу <b>False or False and False</b> ?//a");
rep("( ) True");
rep("(o) False");
quest("Яке значення логічного виразу <b>False or False and False</b> ?//a");
rep("( ) True");
rep("(o) False");
quest("Яке значення логічного виразу <b>False and False or False</b> ?//a");
rep("( ) True");
rep("(o) False");
quest("Яке значення логічного виразу <b>False and False or False</b> ?//a");
rep("( ) True");
rep("(o) False");
quest("Яке значення логічного виразу <b>(False or False) and False</b> ?//a");
rep("( ) True");
rep("(o) False");
quest("Яке значення логічного виразу <b>(False or False) and False</b> ?//a");
rep("( ) True");
rep("(o) False");
quest("Яке значення логічного виразу <b>False and (False or False)</b> ?//a");
rep("( ) True");
rep("(o) False");
quest("Яке значення логічного виразу <b>False and (False or False)</b> ?//a");
rep("( ) True");
rep("(o) False");
quest("Яке значення логічного виразу <b>False xor False and False</b> ?//a");
rep("( ) True");
rep("(o) False");
quest("Яке значення логічного виразу <b>False xor False and False</b> ?//a");
rep("( ) True");
rep("(o) False");
quest("Яке значення логічного виразу <b>False and False xor False</b> ?//a");
rep("( ) True");
rep("(o) False");
quest("Яке значення логічного виразу <b>False and False xor False</b> ?//a");
rep("( ) True");
rep("(o) False");
quest("Яке значення логічного виразу <b>(False xor False) and False</b> ?//a");
rep("( ) True");
rep("(o) False");
quest("Яке значення логічного виразу <b>(False xor False) and False</b> ?//a");
rep("( ) True");
rep("(o) False");
quest("Яке значення логічного виразу <b>False and (False xor False)</b> ?//a");
rep("( ) True");
rep("(o) False");
quest("Яке значення логічного виразу <b>False and (False xor False)</b> ?//a");
rep("( ) True");
rep("(o) False");
quest("Яке значення логічного виразу <b>(False or False) and (False xor False)</b> ?//a");
rep("( ) True");
rep("(o) False");
quest("Яке значення логічного виразу <b>not(False or False) and (False xor False)</b> ?//a");
rep("( ) True");
rep("(o) False");
quest("Яке значення логічного виразу <b>(False or False) and not(False xor False)</b> ?//a");
rep("( ) True");
rep("(o) False");
quest("Яке значення логічного виразу <b>not(False or False) and not(False xor False)</b> ?//a");
rep("(o) True");
rep("( ) False");
quest("Яке значення логічного виразу <b>(False and False) or (False xor False)</b> ?//a");
rep("( ) True");
rep("(o) False");
quest("Яке значення логічного виразу <b>not(False and False) or (False xor False)</b> ?//a");
rep("(o) True");
rep("( ) False");
quest("Яке значення логічного виразу <b>(False and False) or not(False xor False)</b> ?//a");
rep("(o) True");
rep("( ) False");
quest("Яке значення логічного виразу <b>not(False and False) or not(False xor False)</b> ?//a");
rep("(o) True");
rep("( ) False");
quest("Яке значення логічного виразу <b>(False or False) and (False or False)</b> ?//a");
rep("( ) True");
rep("(o) False");
quest("Яке значення логічного виразу <b>not(False or False) and (False or False)</b> ?//a");
rep("( ) True");
rep("(o) False");
quest("Яке значення логічного виразу <b>(False or False) and not(False or False)</b> ?//a");
rep("( ) True");
rep("(o) False");
quest("Яке значення логічного виразу <b>not(False or False) and not(False or False)</b> ?//a");
rep("(o) True");
rep("( ) False");
quest("Яке значення логічного виразу <b>(False and False) or (False or False)</b> ?//a");
rep("( ) True");
rep("(o) False");
quest("Яке значення логічного виразу <b>not(False and False) or (False or False)</b> ?//a");
rep("(o) True");
rep("( ) False");
quest("Яке значення логічного виразу <b>(False and False) or not(False or False)</b> ?//a");
rep("(o) True");
rep("( ) False");
quest("Яке значення логічного виразу <b>not(False and False) or not(False or False)</b> ?//a");
rep("(o) True");
rep("( ) False");
quest("Яке значення логічного виразу <b>True and True or True and not(False) and False and False</b> ?");
rep("(o) True");
rep("( ) False");
quest("Яке значення логічного виразу <b>False or not(False) or True and not(False) and not(True) and True</b> ?");
rep("(o) True");
rep("( ) False");
quest("Яке значення логічного виразу <b>not(False) or True and not(True) or not(True) and False or not(False)</b> ?");
rep("(o) True");
rep("( ) False");
quest("Яке значення логічного виразу <b>not(False) and not(False) and False or True and not(True) or False</b> ?");
rep("( ) True");
rep("(o) False");
quest("Яке значення логічного виразу <b>False or not(False) or not(False) and not(False) or not(True) and True</b> ?");
rep("(o) True");
rep("( ) False");
quest("Яке значення логічного виразу <b>False and False or not(True) or not(False) and not(False) and not(False)</b> ?");
rep("(o) True");
rep("( ) False");
quest("Яке значення логічного виразу <b>not(True) or True or not(True) or not(False) or True and not(False)</b> ?");
rep("(o) True");
rep("( ) False");
quest("Яке значення логічного виразу <b>not(False) or False and not(True) and not(True) or not(True) or not(True)</b> ?");
rep("(o) True");
rep("( ) False");
quest("Яке значення логічного виразу <b>not(False) or False or False or True and False or False</b> ?");
rep("(o) True");
rep("( ) False");
quest("Яке значення логічного виразу <b>True or not(True) or True and not(True) or False and True</b> ?");
rep("(o) True");
rep("( ) False");
quest("Яке значення логічного виразу <b>not(False) and not(True) or False or True or not(True) or not(False)</b> ?");
rep("(o) True");
rep("( ) False");
quest("Яке значення логічного виразу <b>True or True and not(False) and True and False or False</b> ?");
rep("(o) True");
rep("( ) False");
quest("Яке значення логічного виразу <b>not(False) and True and True or not(True) or False and not(True)</b> ?");
rep("(o) True");
rep("( ) False");
quest("Яке значення логічного виразу <b>not(False) or True and False or not(True) or True or False</b> ?");
rep("(o) True");
rep("( ) False");
quest("Яке значення логічного виразу <b>not(False) and False or True or False or not(True) and False</b> ?");
rep("(o) True");
rep("( ) False");
quest("Яке значення логічного виразу <b>not(True) and not(False) and not(True) or not(False) or not(False) and True</b> ?");
rep("(o) True");
rep("( ) False");
quest("Яке значення логічного виразу <b>not(True) and False or not(False) and not(True) and not(False) and True</b> ?");
rep("( ) True");
rep("(o) False");
quest("Яке значення логічного виразу <b>not(False) or False or not(False) and not(False) and not(True) and False</b> ?");
rep("(o) True");
rep("( ) False");
quest("Яке значення логічного виразу <b>False or not(False) or False and False and True and False</b> ?");
rep("(o) True");
rep("( ) False");
quest("Яке значення логічного виразу <b>not(True) and not(False) and True and True and not(False) and not(False)</b> ?");
rep("( ) True");
rep("(o) False");
quest("Яке значення логічного виразу <b>not(False) or True or True or False or not(True) and False</b> ?");
rep("(o) True");
rep("( ) False");
quest("Яке значення логічного виразу <b>not(False) and not(True) and not(False) and not(False) or not(True) and False</b> ?");
rep("( ) True");
rep("(o) False");
quest("Яке значення логічного виразу <b>True and False and False and not(False) or False and False</b> ?");
rep("( ) True");
rep("(o) False");
quest("Яке значення логічного виразу <b>True or not(False) or False and True and False or not(False)</b> ?");
rep("(o) True");
rep("( ) False");
quest("Яке значення логічного виразу <b>False or not(True) and False or not(True) and not(True) and True</b> ?");
rep("( ) True");
rep("(o) False");
quest("Яке значення логічного виразу <b>False and False and not(True) and True or True and False</b> ?");
rep("( ) True");
rep("(o) False");
quest("Яке значення логічного виразу <b>False and not(True) or not(False) or not(False) or True and not(True)</b> ?");
rep("(o) True");
rep("( ) False");
quest("Яке значення логічного виразу <b>not(True) or not(True) or True and False or True and not(False)</b> ?");
rep("(o) True");
rep("( ) False");
quest("Яке значення логічного виразу <b>not(False) and not(False) or not(False) or not(False) and not(True) and False</b> ?");
rep("(o) True");
rep("( ) False");
quest("Яке значення логічного виразу <b>True or False and not(True) or not(True) and False or False</b> ?");
rep("(o) True");
rep("( ) False");
quest("Яке значення логічного виразу <b>not(True) and False or not(False) and not(True) or not(True) and not(False)</b> ?");
rep("( ) True");
rep("(o) False");
quest("Яке значення логічного виразу <b>False and not(False) and True or True and False or not(False)</b> ?");
rep("(o) True");
rep("( ) False");
quest("Яке значення логічного виразу <b>True or True and not(False) or not(True) or not(True) and not(False)</b> ?");
rep("(o) True");
rep("( ) False");
quest("Яке значення логічного виразу <b>True and False and True or False or False and not(False)</b> ?");
rep("( ) True");
rep("(o) False");
quest("Яке значення логічного виразу <b>not(False) or True or not(False) or False or False or not(False)</b> ?");
rep("(o) True");
rep("( ) False");
quest("Яке значення логічного виразу <b>True or not(True) or not(True) or True or False or not(False)</b> ?");
rep("(o) True");
rep("( ) False");
quest("Яке значення логічного виразу <b>not(True) or False and not(True) and not(True) and not(True) or True</b> ?");
rep("(o) True");
rep("( ) False");
quest("Яке значення логічного виразу <b>False or False and not(True) or False or True and True</b> ?");
rep("(o) True");
rep("( ) False");
quest("Яке значення логічного виразу <b>False or True or False or not(True) or not(False) and not(True)</b> ?");
rep("(o) True");
rep("( ) False");
quest("Яке значення логічного виразу <b>True or False and False and not(True) or not(True) and not(False)</b> ?");
rep("(o) True");
rep("( ) False");
quest("Яке значення логічного виразу <b>True and not(False) and not(False) or True and not(True) or not(True)</b> ?");
rep("(o) True");
rep("( ) False");
quest("Яке значення логічного виразу <b>True or not(True) and True or not(True) or not(True) and not(False)</b> ?");
rep("(o) True");
rep("( ) False");
quest("Яке значення логічного виразу <b>False or not(True) or not(False) or True and not(False) or not(False)</b> ?");
rep("(o) True");
rep("( ) False");
quest("Яке значення логічного виразу <b>True and True or False or False or True and True</b> ?");
rep("(o) True");
rep("( ) False");
quest("Яке значення логічного виразу <b>False or True and False and not(True) or not(False) and True</b> ?");
rep("(o) True");
rep("( ) False");
quest("Яке значення логічного виразу <b>False or False and False and not(True) or False or True</b> ?");
rep("(o) True");
rep("( ) False");
quest("Яке значення логічного виразу <b>False or False or not(True) or not(False) or not(False) or not(True)</b> ?");
rep("(o) True");
rep("( ) False");
quest("Яке значення логічного виразу <b>True and not(False) or True or not(True) and False and False</b> ?");
rep("(o) True");
rep("( ) False");
quest("Яке значення логічного виразу <b>False or not(False) and False or not(True) and True and True</b> ?");
rep("( ) True");
rep("(o) False");
quest("Яке значення логічного виразу <b>not(False) or not(False) and False or not(False) or False and not(True)</b> ?");
rep("(o) True");
rep("( ) False");
quest("Яке значення логічного виразу <b>False and not(False) or not(True) and True or not(False) and True</b> ?");
rep("(o) True");
rep("( ) False");
quest("Яке значення логічного виразу <b>not(False) and False or not(True) and not(False) and False and False</b> ?");
rep("( ) True");
rep("(o) False");
